# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 8.5.1.1
    hooks:
      - id: buildifier
      - id: buildifier-lint

  - repo: https://github.com/crate-ci/typos
    rev: v1.48.0
    hooks:
      - id: typos
