"""Repository rule that generates a hub repo with toolchain declarations for all platforms."""

# Maps Bazel platform constraints to our internal platform keys
PLATFORMS = {
    "linux_amd64": struct(
        exec_compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
        target_compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
        binary_ext = "",
    ),
    "linux_arm64": struct(
        exec_compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
        target_compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
        binary_ext = "",
    ),
    "macos_amd64": struct(
        exec_compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
        target_compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
        binary_ext = "",
    ),
    "macos_arm64": struct(
        exec_compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
        target_compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
        binary_ext = "",
    ),
    "windows_amd64": struct(
        exec_compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
        target_compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
        binary_ext = ".exe",
    ),
}

_TOOLCHAIN_TEMPLATE = """\
load("@rules_odin//odin:toolchain.bzl", "odin_toolchain")

odin_toolchain(
    name = "{platform}_toolchain_impl",
    binary_ext = "{binary_ext}",
    compiler = "@{sdk_repo}//:compiler",
    sdk = "@{sdk_repo}//:sdk",
    sdk_root = "external/{sdk_repo}",
    version = "{version}",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {exec_compatible_with},
    target_compatible_with = {target_compatible_with},
    toolchain = ":{platform}_toolchain_impl",
    toolchain_type = "@rules_odin//odin:toolchain_type",
    visibility = ["//visibility:public"],
)
"""

def _toolchains_repo_impl(rctx):
    build_content = "# Generated by rules_odin - do not edit.\n\n"

    for platform in rctx.attr.platforms:
        if platform not in PLATFORMS:
            fail("Unknown platform: " + platform)

        info = PLATFORMS[platform]
        sdk_repo = rctx.attr.sdk_repos[platform]

        build_content += _TOOLCHAIN_TEMPLATE.format(
            platform = platform,
            sdk_repo = sdk_repo,
            version = rctx.attr.odin_version,
            binary_ext = info.binary_ext,
            exec_compatible_with = repr(info.exec_compatible_with),
            target_compatible_with = repr(info.target_compatible_with),
        )

    rctx.file("BUILD.bazel", build_content)

toolchains_repo = repository_rule(
    implementation = _toolchains_repo_impl,
    doc = "Generates a repository with toolchain declarations for all registered Odin SDK platforms.",
    attrs = {
        "odin_version": attr.string(
            doc = "Odin version tag.",
            mandatory = True,
        ),
        "platforms": attr.string_list(
            doc = "List of platform keys that have SDK repos registered.",
            mandatory = True,
        ),
        "sdk_repos": attr.string_dict(
            doc = "Mapping of platform key to SDK repository name.",
            mandatory = True,
        ),
    },
)
